name: Run Python Script

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytesseract
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        env:
          # If you need any environment variables, define them here
        run: |
          python server_ready_alerts_modified.py
